version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: tunequest
      POSTGRES_USER: tunequest
      POSTGRES_PASSWORD: tunequest

  adminer:
    image: adminer
    restart: always
    ports:
      - 3666:8080